import Link from "next/link";
import { Cable, TriangleAlert } from "lucide-react";
import type { CalendarRoomOption, CalendarSourceListItem } from "../calendar-source.types";
import { CalendarSourceForm } from "./calendar-source-form";
import { CalendarConnectionTest, CalendarManualSync, CalendarSourceActiveForm } from "./calendar-source-actions";
import { EmptyState } from "@/components/shared/empty-state";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { RESERVATION_CONFLICT_UI } from "@/features/reservation-conflicts/reservation-conflict.labels";
const formatter = new Intl.DateTimeFormat("ko-KR", { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Tokyo" }); const formatDate = (value: Date | null) => value ? formatter.format(value) : "없음";
function Status({ source }: { source: CalendarSourceListItem }) { return <div className="space-y-1 text-xs"><div className="flex flex-wrap gap-1"><Badge variant={source.latestSyncStatus === "FAILED" || source.latestSyncStatus === "TIMEOUT" ? "destructive" : "outline"}>{source.isSyncing ? "동기화 중" : source.latestSyncStatus ?? "이력 없음"}</Badge>{source.activeConflictCount > 0 && <Badge className="gap-1 bg-amber-500/15 text-amber-800 dark:text-amber-300" variant="outline"><TriangleAlert className="size-3" />{RESERVATION_CONFLICT_UI.label} {source.activeConflictCount}</Badge>}</div><p className="text-muted-foreground">최근 성공 {formatDate(source.lastSuccessfulSyncAt)}</p><p className="text-muted-foreground">최근 실패 {formatDate(source.lastFailedSyncAt)}</p>{source.latestSyncStatus && <p className="tabular-nums text-muted-foreground">VEVENT {source.latestFetchedCount} · +{source.latestCreatedCount} / ~{source.latestUpdatedCount} / 취소 {source.latestCancelledCount}</p>}</div>; }
function Actions({ source, rooms }: { source: CalendarSourceListItem; rooms: CalendarRoomOption[] }) { return <div className="flex flex-wrap gap-2"><CalendarSourceForm rooms={rooms} source={source} /><CalendarConnectionTest id={source.id} /><CalendarManualSync id={source.id} disabled={!source.isActive || source.isSyncing} /><Button nativeButton={false} render={<Link href={`/calendar-sources/${source.id}/sync-logs`} />} size="sm" variant="outline">동기화 이력</Button><CalendarSourceActiveForm id={source.id} isActive={source.isActive} /></div>; }
export function CalendarSourceList({ sources, rooms }: { sources: CalendarSourceListItem[]; rooms: CalendarRoomOption[] }) { if (!sources.length) return <Card><CardContent className="flex min-h-72 items-center"><EmptyState icon={Cable} title="등록된 캘린더 연결이 없습니다" description="객실별 OTA ICS URL을 등록하면 이곳에서 연결 상태를 안전하게 확인할 수 있습니다." /></CardContent></Card>; return <><div className="grid gap-3 lg:hidden">{sources.map((source) => <Card key={source.id}><CardContent className="space-y-3 p-4"><div className="flex justify-between gap-2"><div><p className="font-semibold">{source.name}</p><p className="text-xs text-muted-foreground">{source.propertyName} · {source.roomName}</p></div><Badge variant={source.isActive ? "secondary" : "outline"}>{source.isActive ? "활성" : "비활성"}</Badge></div><p className="break-all font-mono text-xs text-muted-foreground">{source.maskedUrl}</p><Badge variant="outline">{source.provider}</Badge><Status source={source} /><Actions source={source} rooms={rooms} /></CardContent></Card>)}</div><Card className="hidden lg:block"><Table><TableHeader><TableRow><TableHead>숙소 / 객실</TableHead><TableHead>Provider</TableHead><TableHead>이름 / URL</TableHead><TableHead>연결</TableHead><TableHead>동기화 / {RESERVATION_CONFLICT_UI.label}</TableHead><TableHead className="text-right">관리</TableHead></TableRow></TableHeader><TableBody>{sources.map((source) => <TableRow key={source.id}><TableCell><p className="font-medium">{source.propertyName}</p><p className="text-xs text-muted-foreground">{source.roomName}</p></TableCell><TableCell><Badge variant="outline">{source.provider}</Badge></TableCell><TableCell><p className="font-medium">{source.name}</p><p className="max-w-72 truncate font-mono text-xs text-muted-foreground">{source.maskedUrl}</p></TableCell><TableCell><Badge variant={source.isActive ? "secondary" : "outline"}>{source.isActive ? "활성" : "비활성"}</Badge></TableCell><TableCell><Status source={source} /></TableCell><TableCell><div className="flex justify-end"><Actions source={source} rooms={rooms} /></div></TableCell></TableRow>)}</TableBody></Table></Card></>; }
