"use client";
import { useActionState } from "react";
import type { ActionResult } from "@/lib/action-result";
import type { CalendarConnectionResult } from "../calendar-source.types";
import { setCalendarSourceActiveAction, testCalendarSourceAction } from "../calendar-source.actions";
import { syncCalendarSourceAction } from "@/features/calendar-sync/calendar-sync.actions";
import type { CalendarSyncResult } from "@/features/calendar-sync";
import { Button } from "@/components/ui/button";
import { RESERVATION_CONFLICT_UI } from "@/features/reservation-conflicts/reservation-conflict.labels";

const initialTest: ActionResult<CalendarConnectionResult> = { success: true };
export function CalendarSourceActiveForm({ id, isActive }: { id: string; isActive: boolean }) { const [result, action, pending] = useActionState(setCalendarSourceActiveAction, { success: true }); return <form action={action} className="space-y-1"><input type="hidden" name="id" value={id} /><input type="hidden" name="isActive" value={String(!isActive)} /><Button type="submit" size="sm" variant={isActive ? "outline" : "secondary"} disabled={pending}>{pending ? "변경 중" : isActive ? "비활성화" : "활성화"}</Button>{!result.success && <p className="max-w-48 text-xs text-destructive">{result.message}</p>}</form>; }
export function CalendarConnectionTest({ id }: { id: string }) { const [result, action, pending] = useActionState(testCalendarSourceAction, initialTest); return <div className="space-y-2"><form action={action}><input type="hidden" name="id" value={id} /><Button type="submit" size="sm" variant="secondary" disabled={pending}>{pending ? "테스트 중" : "연결 테스트"}</Button></form>{result.message && <div aria-live="polite" className={`max-w-72 rounded-md p-2 text-xs ${result.success ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" : "bg-destructive/10 text-destructive"}`}><p className="font-medium">{result.message}</p>{result.success && result.data && <p className="mt-1 leading-5">{result.data.provider} · {result.data.responseTimeMs}ms · 이벤트 {result.data.eventCount}개<br />UID {result.data.uidCount} · DTSTART {result.data.startCount} · DTEND {result.data.endCount} · SUMMARY {result.data.summaryCount}<br />가져온 시각 {new Intl.DateTimeFormat("ko-KR", { dateStyle: "short", timeStyle: "medium" }).format(new Date(result.data.fetchedAt))}<br />Content-Type: {result.data.contentType ?? "없음"}</p>}</div>}</div>; }
const initialSync: ActionResult<CalendarSyncResult> = { success: true };
export function CalendarManualSync({ id, disabled }: { id: string; disabled?: boolean }) { const [result, action, pending] = useActionState(syncCalendarSourceAction, initialSync); return <div className="space-y-2"><form action={action}><input type="hidden" name="calendarSourceId" value={id} /><Button type="submit" size="sm" disabled={disabled || pending}>{pending ? "동기화 중" : "동기화"}</Button></form>{result.message && <div aria-live="polite" className={`max-w-72 rounded-md p-2 text-xs ${result.success ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" : "bg-destructive/10 text-destructive"}`}><p className="font-medium">{result.message}</p>{result.success && result.data && <p className="mt-1 leading-5">VEVENT {result.data.fetchedCount} · 제외 {result.data.excludedCount}<br />생성 {result.data.createdCount} · 수정 {result.data.updatedCount} · 취소 {result.data.cancelledCount} · 동일 {result.data.unchangedCount}<br />활성 {RESERVATION_CONFLICT_UI.label} {result.data.activeConflictCount} · 신규 {result.data.createdConflictCount} · 해제 {result.data.resolvedConflictCount}</p>}</div>}</div>; }
