import { useTranslations, useLocale } from "next-intl";import Link from "next/link";
import { Cable, TriangleAlert } from "lucide-react";
import type { CalendarRoomOption, CalendarSourceListItem } from "../calendar-source.types";
import { CalendarSourceForm } from "./calendar-source-form";
import { CalendarSourceUrlReplaceDialog } from "./calendar-source-url-replace-dialog";
import { CalendarConnectionTest, CalendarManualSync, CalendarSourceActiveForm } from "./calendar-source-actions";
import { EmptyState } from "@/components/shared/empty-state";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getProviderLabel } from "@/features/reservations/provider-visuals";
import { getReservationSyncStatusLabel } from "@/features/reservations/reservation-status-meta";

function Status({ source }: {source: CalendarSourceListItem;}) {const locale = useLocale(),localeTag = locale === "ja" ? "ja-JP" : "ko-KR";const formatter = new Intl.DateTimeFormat(localeTag, { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Tokyo" });const i18n = useTranslations();const formatDate = (value: Date | null) => value ? formatter.format(value) : i18n("auto.m0047");return <div className="space-y-1 text-xs"><div className="flex flex-wrap gap-1"><Badge className={source.connectionStatus === "RECONNECT_REQUIRED" ? "border-amber-500/40 bg-amber-500/10 text-amber-800 dark:text-amber-300" : undefined} variant={source.connectionStatus === "RECONNECT_REQUIRED" ? "outline" : source.latestSyncStatus === "FAILED" || source.latestSyncStatus === "TIMEOUT" ? "destructive" : "outline"}>{source.connectionStatus === "RECONNECT_REQUIRED" ? i18n("calendarStatus.RECONNECT_REQUIRED") : source.isSyncing ? i18n("sync.statuses.RUNNING") : source.latestSyncStatus ? getReservationSyncStatusLabel(source.latestSyncStatus, i18n) : i18n("auto.m0295")}</Badge>{source.activeConflictCount > 0 && <Badge className="gap-1 bg-amber-500/15 text-amber-800 dark:text-amber-300" variant="outline"><TriangleAlert className="size-3" />{i18n("conflict.label")} {source.activeConflictCount}</Badge>}</div>{source.connectionStatus === "RECONNECT_REQUIRED" && <p className="max-w-72 text-amber-800 dark:text-amber-300">{i18n("calendarFeedSafety.reconnectMessage")}</p>}<p className="text-muted-foreground">{i18n("auto.m0296")}{formatDate(source.lastSuccessfulSyncAt)}</p><p className="text-muted-foreground">{i18n("auto.m0297")}{formatDate(source.lastFailedSyncAt)}</p>{source.latestSyncStatus && <p className="tabular-nums text-muted-foreground">{i18n("technical.vevent")} {source.latestFetchedCount} · +{source.latestCreatedCount} / ~{source.latestUpdatedCount}{i18n("auto.m0298")}{source.latestCancelledCount}</p>}</div>;}
function Actions({ source, rooms }: {source: CalendarSourceListItem;rooms: CalendarRoomOption[];}) {const i18n = useTranslations();return <div className="flex flex-wrap gap-2"><CalendarSourceForm rooms={rooms} source={source} /><CalendarSourceUrlReplaceDialog calendarSourceId={source.id} provider={source.provider} reconnectRequired={source.connectionStatus === "RECONNECT_REQUIRED"} /><CalendarConnectionTest id={source.id} /><CalendarManualSync id={source.id} disabled={!source.isActive || source.isSyncing || source.connectionStatus === "RECONNECT_REQUIRED"} /><Button nativeButton={false} render={<Link href={`/calendar-sources/${source.id}/sync-logs`} />} size="sm" variant="outline">{i18n("auto.m0019")}</Button><CalendarSourceActiveForm id={source.id} isActive={source.isActive} /></div>;}
export function CalendarSourceList({ sources, rooms }: {sources: CalendarSourceListItem[];rooms: CalendarRoomOption[];}) {const i18n = useTranslations();if (!sources.length) return <Card><CardContent className="flex min-h-72 items-center"><EmptyState icon={Cable} title={i18n("auto.m0299")} description={i18n("auto.m0300")} /></CardContent></Card>;return <><div className="grid gap-3 lg:hidden">{sources.map((source) => <Card key={source.id}><CardContent className="space-y-3 p-4"><div className="flex justify-between gap-2"><div><p className="font-semibold">{source.name}</p><p className="text-xs text-muted-foreground">{source.propertyName} · {source.roomName}</p></div><Badge variant={source.isActive ? "secondary" : "outline"}>{source.isActive ? i18n("auto.m0210") : i18n("auto.m0115")}</Badge></div><p className="break-all font-mono text-xs text-muted-foreground">{source.maskedUrl}</p><Badge variant="outline">{getProviderLabel(source.provider, i18n)}</Badge><Status source={source} /><Actions source={source} rooms={rooms} /></CardContent></Card>)}</div><Card className="hidden lg:block"><Table><TableHeader><TableRow><TableHead>{i18n("auto.m0005")}</TableHead><TableHead>{i18n("technical.provider")}</TableHead><TableHead>{i18n("auto.m0301")}</TableHead><TableHead>{i18n("auto.m0006")}</TableHead><TableHead>{i18n("auto.m0302")}{i18n("conflict.label")}</TableHead><TableHead className="text-right">{i18n("navigation.groups.management")}</TableHead></TableRow></TableHeader><TableBody>{sources.map((source) => <TableRow key={source.id}><TableCell><p className="font-medium">{source.propertyName}</p><p className="text-xs text-muted-foreground">{source.roomName}</p></TableCell><TableCell><Badge variant="outline">{getProviderLabel(source.provider, i18n)}</Badge></TableCell><TableCell><p className="font-medium">{source.name}</p><p className="max-w-72 truncate font-mono text-xs text-muted-foreground">{source.maskedUrl}</p></TableCell><TableCell><Badge variant={source.isActive ? "secondary" : "outline"}>{source.isActive ? i18n("auto.m0210") : i18n("auto.m0115")}</Badge></TableCell><TableCell><Status source={source} /></TableCell><TableCell><div className="flex justify-end"><Actions source={source} rooms={rooms} /></div></TableCell></TableRow>)}</TableBody></Table></Card></>;}
