"use client";
import { useActionState } from "react";
import { Plus, Settings2 } from "lucide-react";
import type { CalendarProviderType } from "@/lib/generated/prisma/enums";
import type { CalendarRoomOption } from "../calendar-source.types";
import { createCalendarSourceAction, updateCalendarSourceAction } from "../calendar-source.actions";
import { INITIAL_ACTION_RESULT } from "@/lib/action-result";
import { ActionMessage } from "@/components/shared/action-message";
import { FieldError } from "@/components/shared/field-error";
import { SubmitButton } from "@/components/shared/submit-button";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

const providers = [{ value: "BOOKING", label: "Booking.com" }, { value: "AIRBNB", label: "Airbnb" }, { value: "AGODA", label: "Agoda" }] as const;
export interface EditableCalendarSource { id: string; roomId: string; provider: CalendarProviderType; name: string; isActive: boolean }
export function CalendarSourceForm({ rooms, source }: { rooms: CalendarRoomOption[]; source?: EditableCalendarSource }) {
  const [result, formAction] = useActionState(source ? updateCalendarSourceAction : createCalendarSourceAction, INITIAL_ACTION_RESULT);
  return <Dialog><DialogTrigger render={<Button variant={source ? "outline" : "default"} size={source ? "sm" : "default"} disabled={!source && rooms.length === 0} />}>{source ? <><Settings2 />수정</> : <><Plus />연결 등록</>}</DialogTrigger><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{source ? "캘린더 연결 수정" : "새 캘린더 연결"}</DialogTitle><DialogDescription>ICS URL은 비밀번호처럼 보호됩니다. 저장 후에는 전체 주소를 다시 표시하지 않습니다.</DialogDescription></DialogHeader><form action={formAction} className="space-y-4">{source && <input type="hidden" name="id" value={source.id} />}<div className="space-y-1.5"><Label htmlFor={`source-room-${source?.id ?? "new"}`}>객실</Label><select id={`source-room-${source?.id ?? "new"}`} name="roomId" defaultValue={source?.roomId ?? ""} className="h-8 w-full rounded-lg border border-input bg-background px-2.5 text-sm" required><option value="" disabled>객실을 선택하세요</option>{rooms.map((room) => <option key={room.id} value={room.id}>{room.propertyName} · {room.name}{room.isActive && room.propertyIsActive ? "" : " (비활성)"}</option>)}</select><FieldError errors={!result.success ? result.fieldErrors?.roomId : undefined} /></div><div className="space-y-1.5"><Label htmlFor={`source-provider-${source?.id ?? "new"}`}>OTA</Label><select id={`source-provider-${source?.id ?? "new"}`} name="provider" defaultValue={source?.provider ?? ""} className="h-8 w-full rounded-lg border border-input bg-background px-2.5 text-sm" required><option value="" disabled>Provider를 선택하세요</option>{providers.map((provider) => <option key={provider.value} value={provider.value}>{provider.label}</option>)}</select><FieldError errors={!result.success ? result.fieldErrors?.provider : undefined} /></div><div className="space-y-1.5"><Label htmlFor={`source-name-${source?.id ?? "new"}`}>연결 이름</Label><Input id={`source-name-${source?.id ?? "new"}`} name="name" defaultValue={source?.name} maxLength={100} placeholder="예: Booking.com" required /><FieldError errors={!result.success ? result.fieldErrors?.name : undefined} /></div><div className="space-y-1.5"><Label htmlFor={`source-url-${source?.id ?? "new"}`}>ICS URL</Label><Input id={`source-url-${source?.id ?? "new"}`} name="calendarUrl" type="url" autoComplete="off" maxLength={2000} placeholder={source ? "변경할 때만 새 URL 입력" : "https://…"} required={!source} /><p className="text-xs text-muted-foreground">{source ? "기존 URL은 보안상 표시하지 않습니다. 비워 두면 변경되지 않습니다." : "HTTPS와 선택한 OTA의 공식 호스트만 허용됩니다."}</p><FieldError errors={!result.success ? result.fieldErrors?.calendarUrl : undefined} /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isActive" value="true" defaultChecked={source?.isActive ?? true} className="size-4" />활성 상태로 사용</label><input type="hidden" name="isActive" value="false" /><ActionMessage result={result} /><div className="flex justify-end"><SubmitButton>{source ? "변경 저장" : "연결 등록"}</SubmitButton></div></form></DialogContent></Dialog>;
}
