import { Cable } from "lucide-react";
import type { CalendarRoomOption, CalendarSourceListItem } from "../calendar-source.types";
import { EmptyState } from "@/components/shared/empty-state";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { CalendarConnectionTest, CalendarManualSync, CalendarSourceActiveForm } from "./calendar-source-actions";
import { CalendarSourceForm } from "./calendar-source-form";

function formatDate(value: Date | null) { return value ? new Intl.DateTimeFormat("ko-KR", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Tokyo" }).format(value) : "없음"; }
export function CalendarSourceList({ sources, rooms }: { sources: CalendarSourceListItem[]; rooms: CalendarRoomOption[] }) { if (!sources.length) return <Card><CardContent className="flex min-h-72 items-center"><EmptyState icon={Cable} title="등록된 캘린더 연결이 없습니다" description="객실별 OTA ICS URL을 등록하면 이곳에서 연결 상태를 안전하게 확인할 수 있습니다." /></CardContent></Card>; return <><div className="grid gap-3 lg:hidden">{sources.map((source) => <Card key={source.id}><CardContent className="space-y-3 p-4"><div className="flex justify-between gap-2"><div><p className="font-semibold">{source.name}</p><p className="text-xs text-muted-foreground">{source.propertyName} · {source.roomName}</p></div><Badge variant={source.isActive ? "secondary" : "outline"}>{source.isActive ? "활성" : "비활성"}</Badge></div><p className="break-all font-mono text-xs text-muted-foreground">{source.maskedUrl}</p><div className="flex justify-between text-xs"><Badge variant="outline">{source.provider}</Badge><span className="text-muted-foreground">최근 동기화 {formatDate(source.lastSyncedAt)}</span></div><div className="flex flex-wrap gap-2"><CalendarSourceForm rooms={rooms} source={source} /><CalendarConnectionTest id={source.id} /><CalendarManualSync id={source.id} disabled={!source.isActive} /><CalendarSourceActiveForm id={source.id} isActive={source.isActive} /></div></CardContent></Card>)}</div><Card className="hidden lg:block"><Table><TableHeader><TableRow><TableHead>숙소 / 객실</TableHead><TableHead>Provider</TableHead><TableHead>이름 / URL</TableHead><TableHead>상태</TableHead><TableHead>최근 동기화</TableHead><TableHead className="text-right">관리</TableHead></TableRow></TableHeader><TableBody>{sources.map((source) => <TableRow key={source.id}><TableCell><p className="font-medium">{source.propertyName}</p><p className="text-xs text-muted-foreground">{source.roomName}</p></TableCell><TableCell><Badge variant="outline">{source.provider}</Badge></TableCell><TableCell><p className="font-medium">{source.name}</p><p className="max-w-80 truncate font-mono text-xs text-muted-foreground">{source.maskedUrl}</p></TableCell><TableCell><Badge variant={source.isActive ? "secondary" : "outline"}>{source.isActive ? "활성" : "비활성"}</Badge></TableCell><TableCell>{formatDate(source.lastSyncedAt)}</TableCell><TableCell><div className="flex justify-end gap-2"><CalendarSourceForm rooms={rooms} source={source} /><CalendarConnectionTest id={source.id} /><CalendarManualSync id={source.id} disabled={!source.isActive} /><CalendarSourceActiveForm id={source.id} isActive={source.isActive} /></div></TableCell></TableRow>)}</TableBody></Table></Card></>; }
