"use client";import { useTranslations, useLocale } from "next-intl";
import { useActionState } from "react";
import type { ActionResult } from "@/lib/action-result";
import type { CalendarConnectionResult } from "../calendar-source.types";
import { setCalendarSourceActiveAction, testCalendarSourceAction } from "../calendar-source.actions";
import { syncCalendarSourceAction } from "@/features/calendar-sync/calendar-sync.actions";
import type { CalendarSyncResult } from "@/features/calendar-sync";
import { Button } from "@/components/ui/button";
import { getProviderLabel } from "@/features/reservations/provider-visuals";

const initialTest: ActionResult<CalendarConnectionResult> = { success: true };
export function CalendarSourceActiveForm({ id, isActive }: {id: string;isActive: boolean;}) {const i18n = useTranslations();const [result, action, pending] = useActionState(setCalendarSourceActiveAction, { success: true });return <form action={action} className="space-y-1"><input type="hidden" name="id" value={id} /><input type="hidden" name="isActive" value={String(!isActive)} /><Button type="submit" size="sm" variant={isActive ? "outline" : "secondary"} disabled={pending}>{pending ? i18n("auto.m0265") : isActive ? i18n("auto.m0266") : i18n("auto.m0267")}</Button>{!result.success && <p className="max-w-48 text-xs text-destructive">{result.message}</p>}</form>;}
export function CalendarConnectionTest({ id }: {id: string;}) {const locale = useLocale(),localeTag = locale === "ja" ? "ja-JP" : "ko-KR";const i18n = useTranslations();const [result, action, pending] = useActionState(testCalendarSourceAction, initialTest);return <div className="space-y-2"><form action={action}><input type="hidden" name="id" value={id} /><Button type="submit" size="sm" variant="secondary" disabled={pending}>{pending ? i18n("auto.m0268") : i18n("auto.m0269")}</Button></form>{result.message && <div aria-live="polite" className={`max-w-72 rounded-md p-2 text-xs ${result.success ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" : "bg-destructive/10 text-destructive"}`}><p className="font-medium">{result.message}</p>{result.success && result.data && <p className="mt-1 leading-5">{getProviderLabel(result.data.provider, i18n)} · {result.data.responseTimeMs}{i18n("auto.m0270")}{result.data.eventCount}{i18n("auto.m0271")}<br />{i18n("technical.uid")} {result.data.uidCount} · {i18n("technical.dtstart")} {result.data.startCount} · {i18n("technical.dtend")} {result.data.endCount} · {i18n("technical.summary")} {result.data.summaryCount}<br />{i18n("auto.m0272")}{new Intl.DateTimeFormat(localeTag, { dateStyle: "short", timeStyle: "medium" }).format(new Date(result.data.fetchedAt))}<br />{i18n("technical.contentType")}: {result.data.contentType ?? i18n("auto.m0047")}</p>}</div>}</div>;}
const initialSync: ActionResult<CalendarSyncResult> = { success: true };
export function CalendarManualSync({ id, disabled }: {id: string;disabled?: boolean;}) {const i18n = useTranslations();
  const [result, action, pending] = useActionState(syncCalendarSourceAction, initialSync);
  const warning = result.success && result.data?.warning;
  return <div className="space-y-2"><form action={action}><input type="hidden" name="calendarSourceId" value={id} /><Button type="submit" size="sm" disabled={disabled || pending}>{pending ? i18n("sync.statuses.RUNNING") : i18n("common.sync")}</Button></form>{result.message && <div aria-live="polite" className={`max-w-80 rounded-md p-2 text-xs ${warning ? "bg-amber-500/10 text-amber-800 dark:text-amber-200" : result.success ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" : "bg-destructive/10 text-destructive"}`}><p className="font-medium">{result.message}</p>{result.success && result.data && <div className="mt-1 leading-5"><p>{i18n("auto.m0032")}{result.data.fetchedCount}{i18n("auto.m0274")}{result.data.reservationEventCount}{i18n("auto.m0038")}{result.data.blockedEventCount}<br />{i18n("auto.m0275")}{result.data.unknownEventCount}{i18n("auto.m0041")}{result.data.failedEventCount}{i18n("auto.m0276")}{result.data.excludedCount}<br />{i18n("auto.m0025")}{result.data.createdCount}{i18n("auto.m0277")}{result.data.updatedCount}{i18n("auto.m0278")}{result.data.cancelledCount}{i18n("auto.m0279")}{result.data.unchangedCount}<br />{i18n("sync.health.dbReservations")} {result.data.currentSourceOperationalReservationCount}<br />{i18n("auto.m0210")}{i18n("conflict.label")} {result.data.activeConflictCount}{i18n("auto.m0280")}{result.data.createdConflictCount}{i18n("auto.m0281")}{result.data.resolvedConflictCount}</p>{warning && result.data.warningReasons.length > 0 && <ul className="mt-1 list-disc pl-4">{result.data.warningReasons.map((reason) => <li key={reason}>{i18n(`sync.health.reasons.${reason}`)}</li>)}</ul>}</div>}</div>}</div>;
}
