import { addDays, addMonths, format, startOfMonth } from "date-fns";
import { getDashboardTodayRange } from "../../../dashboard/dashboard-time";
import type { OccupancyPeriod } from "./occupancy";
export type OccupancyPeriodKey = "this-month" | "next-month" | "last-30-days" | "custom";
export const OCCUPANCY_PERIOD_OPTIONS = [{ value: "this-month", label: "이번 달" }, { value: "next-month", label: "다음 달" }, { value: "last-30-days", label: "최근 30일" }, { value: "custom", label: "사용자 지정" }] as const;
const LAST_30_DAYS = 30; const MS_PER_CALENDAR_DAY = 86_400_000;
function atTokyoStart(dateText: string) { const date = new Date(`${dateText}T00:00:00+09:00`); return Number.isFinite(date.getTime()) ? date : null; }
function build(start: Date, endExclusive: Date): OccupancyPeriod { return { start, endExclusive, startLabel: format(start, "yyyy-MM-dd"), endLabel: format(addDays(endExclusive, -1), "yyyy-MM-dd"), nightCount: Math.max(0, Math.round((Date.UTC(endExclusive.getUTCFullYear(), endExclusive.getUTCMonth(), endExclusive.getUTCDate()) - Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), start.getUTCDate())) / MS_PER_CALENDAR_DAY)) }; }
export function resolveOccupancyPeriod(input: { period?: string; from?: string; to?: string }, now = new Date()): { key: OccupancyPeriodKey; period: OccupancyPeriod } { const today = getDashboardTodayRange(now).start; if (input.from && input.to) { const start = atTokyoStart(input.from); const inclusiveEnd = atTokyoStart(input.to); if (start && inclusiveEnd && start <= inclusiveEnd) return { key: "custom", period: build(start, addDays(inclusiveEnd, 1)) }; } if (input.period === "next-month") { const start = startOfMonth(addMonths(today, 1)); return { key: "next-month", period: build(start, addMonths(start, 1)) }; } if (input.period === "last-30-days") return { key: "last-30-days", period: build(addDays(today, -(LAST_30_DAYS - 1)), addDays(today, 1)) }; const start = startOfMonth(today); return { key: "this-month", period: build(start, addMonths(start, 1)) }; }
