"use client";

import { useActionState, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { ActionMessage } from "@/components/shared/action-message";
import type { ActionResult } from "@/lib/action-result";
import { USER_ROLE_LABELS, type UserRole } from "@/features/access-control/domain/access-control";
import type { PropertyOption } from "@/features/properties/property.types";
import type { CalendarRoomOption } from "@/features/calendar-sources/calendar-source.types";
import type { ManagedUserSummary } from "../user-management.repository";
import { createManagedUserAction, resetManagedUserPasswordAction, setManagedUserActiveAction, updateManagedUserRoleAction, updateStaffAssignmentsAction } from "../user-management.actions";

const initialState: ActionResult = { success: false, message: "" };
const dateFormatter = new Intl.DateTimeFormat("ko-KR", { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Tokyo" });

function CreateUserForm({ actorRole, companyId, properties, rooms }: { actorRole: UserRole; companyId: string; properties: PropertyOption[]; rooms: CalendarRoomOption[] }) {
  const [state, action, pending] = useActionState(createManagedUserAction, initialState);
  const [role, setRole] = useState<UserRole>(actorRole === "ADMIN" ? "STAFF" : "ADMIN");
  return <form action={action} className="grid gap-3 rounded-lg border p-3 sm:grid-cols-2 xl:grid-cols-4"><Input name="name" placeholder="이름" required /><Input name="email" type="email" placeholder="이메일" required /><Input name="password" type="password" minLength={8} placeholder="초기 비밀번호" required /><select name="role" value={role} onChange={(event) => setRole(event.target.value as UserRole)} className="h-8 rounded-lg border bg-background px-2 text-sm">{actorRole === "DEVELOPER" && <option value="ADMIN">관리자</option>}<option value="STAFF">직원</option></select><input type="hidden" name="companyId" value={companyId} /><label className="flex items-center gap-2 text-sm sm:col-span-2 xl:col-span-4"><input type="checkbox" name="isActive" value="true" defaultChecked className="size-4 accent-primary" />생성 즉시 활성화</label>{role === "STAFF" && <><fieldset className="space-y-1 sm:col-span-2"><legend className="text-xs font-medium">숙소 배정</legend><div className="flex flex-wrap gap-2">{properties.map((property) => <label key={property.id} className="flex items-center gap-1 text-xs"><input type="checkbox" name="propertyIds" value={property.id} />{property.name}</label>)}</div></fieldset><fieldset className="space-y-1 sm:col-span-2"><legend className="text-xs font-medium">객실 배정</legend><div className="flex max-h-20 flex-wrap gap-2 overflow-y-auto">{rooms.map((room) => <label key={room.id} className="flex items-center gap-1 text-xs"><input type="checkbox" name="roomIds" value={room.id} />{room.name}</label>)}</div></fieldset></>}<div className="flex items-center gap-3 sm:col-span-2 xl:col-span-4"><Button type="submit" disabled={pending}>계정 생성</Button><ActionMessage state={state} /></div></form>;
}

function ManagedUserActions({ user, actorRole, actorUserId, companyId, properties, rooms }: { user: ManagedUserSummary; actorRole: UserRole; actorUserId: string; companyId: string; properties: PropertyOption[]; rooms: CalendarRoomOption[] }) {
  const [activeState, activeAction, activePending] = useActionState(setManagedUserActiveAction, initialState);
  const [passwordState, passwordAction, passwordPending] = useActionState(resetManagedUserPasswordAction, initialState);
  const [roleState, roleAction, rolePending] = useActionState(updateManagedUserRoleAction, initialState);
  const [assignmentState, assignmentAction, assignmentPending] = useActionState(updateStaffAssignmentsAction, initialState);
  const isSelf = user.id === actorUserId;
  return <details className="border-t pt-2"><summary className="cursor-pointer text-xs font-medium">계정 관리</summary><div className="mt-3 grid gap-3 lg:grid-cols-2"><form action={activeAction} className="flex items-center gap-2"><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="isActive" value={String(!user.isActive)} /><Button type="submit" size="sm" variant="outline" disabled={activePending || isSelf}>{user.isActive ? "비활성화" : "활성화"}</Button><ActionMessage state={activeState} /></form><form action={passwordAction} className="flex items-center gap-2"><input type="hidden" name="userId" value={user.id} /><Input name="password" type="password" minLength={8} placeholder="새 초기 비밀번호" required className="max-w-52" /><Button type="submit" size="sm" variant="outline" disabled={passwordPending || isSelf}>초기화</Button><ActionMessage state={passwordState} /></form><form action={roleAction} className="flex items-center gap-2 lg:col-span-2"><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="companyId" value={companyId} /><select name="role" defaultValue={user.role} disabled={actorRole !== "DEVELOPER" || isSelf} className="h-8 rounded-lg border bg-background px-2 text-sm">{user.role === "DEVELOPER" && <option value="DEVELOPER" disabled>개발자 (Seed 전용)</option>}<option value="ADMIN">관리자</option><option value="STAFF">직원</option></select><Button type="submit" size="sm" variant="outline" disabled={rolePending || actorRole !== "DEVELOPER" || isSelf}>역할 저장</Button><ActionMessage state={roleState} /></form>{user.role === "STAFF" && <form action={assignmentAction} className="space-y-2 rounded-md border p-2 lg:col-span-2"><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="companyId" value={companyId} /><p className="text-xs font-medium">직원 배정</p><div className="flex flex-wrap gap-2">{properties.map((property) => <label key={property.id} className="flex items-center gap-1 text-xs"><input type="checkbox" name="propertyIds" value={property.id} defaultChecked={user.propertyIds.includes(property.id)} />{property.name}</label>)}</div><div className="flex flex-wrap gap-2">{rooms.map((room) => <label key={room.id} className="flex items-center gap-1 text-xs"><input type="checkbox" name="roomIds" value={room.id} defaultChecked={user.roomIds.includes(room.id)} />{room.name}</label>)}</div><div className="flex items-center gap-2"><Button type="submit" size="sm" disabled={assignmentPending}>배정 저장</Button><ActionMessage state={assignmentState} /></div></form>}</div></details>;
}

export function UserManagementCard({ users, actorRole, actorUserId, companyId, properties, rooms }: { users: ManagedUserSummary[]; actorRole: UserRole; actorUserId: string; companyId: string; properties: PropertyOption[]; rooms: CalendarRoomOption[] }) {
  return <Card><CardHeader><CardTitle className="text-base">계정 관리</CardTitle><p className="text-sm text-muted-foreground">개발자 계정은 Seed에서만 생성합니다. 관리자와 직원은 권한 범위 안에서 생성할 수 있습니다.</p></CardHeader><CardContent className="space-y-4"><CreateUserForm actorRole={actorRole} companyId={companyId} properties={properties} rooms={rooms} /><div className="space-y-2">{users.map((user) => <article key={user.id} className="rounded-lg border p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-sm font-semibold">{user.name}</p><p className="text-xs text-muted-foreground">{user.email} · {user.companyNames.join(", ") || "시스템 계정"}</p><p className="text-[11px] text-muted-foreground">최근 로그인 {user.lastLoginAt ? dateFormatter.format(user.lastLoginAt) : "없음"}</p></div><div className="flex gap-1"><Badge variant="outline">{USER_ROLE_LABELS[user.role]}</Badge><Badge variant={user.isActive ? "secondary" : "outline"}>{user.isActive ? "활성" : "비활성"}</Badge></div></div><ManagedUserActions user={user} actorRole={actorRole} actorUserId={actorUserId} companyId={companyId} properties={properties} rooms={rooms} /></article>)}</div></CardContent></Card>;
}
