"use server";
import { revalidatePath } from "next/cache";
import { getCurrentAccessContext, getRolePreviewWriteBlock, hasPermission, PERMISSIONS } from "@/features/access-control";
import type { ActionResult } from "@/lib/action-result";
import { prisma } from "@/lib/prisma";
import { memberStatusSchema, updateMemberSchema } from "./member-management.schemas";
import { assertCanManageMember, assertLastActiveAdminSafe } from "./domain/member-policy";

const FORBIDDEN_MESSAGE = "해당 사용자를 관리할 권한이 없습니다.";
const forbidden = (): ActionResult => ({ success: false, status: 403, errorCode: "FORBIDDEN", message: FORBIDDEN_MESSAGE });
async function managementContext(companyId: string) { const context = await getCurrentAccessContext(); if (!context) return null; if (getRolePreviewWriteBlock(context)) return context; if (!hasPermission(context.role, PERMISSIONS.USER_MANAGE) || context.role === "STAFF") return null; if (context.role !== "DEVELOPER" && context.activeCompanyId !== companyId) return null; if (context.role === "DEVELOPER" && !context.availableCompanies?.some((company) => company.id === companyId)) return null; return context; }
async function validPropertyIds(companyId: string, propertyIds: string[]) { const unique = [...new Set(propertyIds)]; const count = await prisma.property.count({ where: { companyId, id: { in: unique }, isActive: true } }); return count === unique.length ? unique : null; }

export async function updateCompanyMemberAction(_state: ActionResult, formData: FormData): Promise<ActionResult> {
  const parsed = updateMemberSchema.safeParse({ companyId: formData.get("companyId"), membershipId: formData.get("membershipId"), name: formData.get("name"), role: formData.get("role"), propertyIds: formData.getAll("propertyIds") }); if (!parsed.success) return { success: false, message: "구성원 설정을 확인해 주세요.", fieldErrors: parsed.error.flatten().fieldErrors };
  const context = await managementContext(parsed.data.companyId); if (!context) return forbidden(); const previewBlock = getRolePreviewWriteBlock(context); if (previewBlock) return previewBlock; const target = await prisma.companyMembership.findFirst({ where: { id: parsed.data.membershipId, companyId: parsed.data.companyId }, select: { id: true, userId: true, role: true, status: true, user: { select: { name: true } }, propertyAccesses: { select: { propertyId: true } } } }); if (!target) return forbidden();
  try { assertCanManageMember({ actorRole: context.role, actorUserId: context.userId, targetUserId: target.userId, targetRole: target.role, sameCompany: true, action: "CHANGE_ROLE" }); const activeAdminCount = await prisma.companyMembership.count({ where: { companyId: parsed.data.companyId, role: "ADMIN", status: "ACTIVE" } }); assertLastActiveAdminSafe({ currentRole: target.role, nextRole: parsed.data.role, activeAdminCount }); } catch (error) { return { success: false, message: error instanceof Error ? error.message : FORBIDDEN_MESSAGE }; }
  const propertyIds = await validPropertyIds(parsed.data.companyId, parsed.data.propertyIds); if (!propertyIds) return { success: false, message: "선택한 숙소를 확인해 주세요." };
  await prisma.$transaction(async (tx) => { await tx.user.update({ where: { id: target.userId }, data: { name: parsed.data.name, sessionVersion: { increment: 1 } } }); await tx.companyMembership.update({ where: { id: target.id }, data: { role: parsed.data.role } }); await tx.propertyAccess.deleteMany({ where: { membershipId: target.id } }); if (parsed.data.role === "STAFF" && propertyIds.length) await tx.propertyAccess.createMany({ data: propertyIds.map((propertyId) => ({ membershipId: target.id, propertyId })) }); await tx.auditLog.create({ data: { actorUserId: context.userId, targetUserId: target.userId, targetCompanyId: parsed.data.companyId, action: "MEMBER_ROLE_CHANGED", details: { companyId: parsed.data.companyId, before: { role: target.role, propertyIds: target.propertyAccesses.map((item) => item.propertyId) }, after: { role: parsed.data.role, propertyIds: parsed.data.role === "STAFF" ? propertyIds : [] } } } }); });
  revalidatePath("/settings/members"); return { success: true, message: "구성원 권한을 저장했습니다." };
}

export async function setCompanyMemberActiveAction(_state: ActionResult, formData: FormData): Promise<ActionResult> {
  const parsed = memberStatusSchema.safeParse({ companyId: formData.get("companyId"), membershipId: formData.get("membershipId"), active: formData.get("active") }); if (!parsed.success) return { success: false, message: "잘못된 요청입니다." };
  const context = await managementContext(parsed.data.companyId); if (!context) return forbidden(); const previewBlock = getRolePreviewWriteBlock(context); if (previewBlock) return previewBlock; const target = await prisma.companyMembership.findFirst({ where: { id: parsed.data.membershipId, companyId: parsed.data.companyId }, select: { id: true, userId: true, role: true, status: true } }); if (!target) return forbidden();
  try { assertCanManageMember({ actorRole: context.role, actorUserId: context.userId, targetUserId: target.userId, targetRole: target.role, sameCompany: true, action: parsed.data.active ? "REACTIVATE_MEMBER" : "DISABLE_MEMBER" }); const activeAdminCount = await prisma.companyMembership.count({ where: { companyId: parsed.data.companyId, role: "ADMIN", status: "ACTIVE" } }); assertLastActiveAdminSafe({ currentRole: target.role, disabling: !parsed.data.active, activeAdminCount }); } catch (error) { return { success: false, message: error instanceof Error ? error.message : FORBIDDEN_MESSAGE }; }
  await prisma.$transaction([prisma.companyMembership.update({ where: { id: target.id }, data: { status: parsed.data.active ? "ACTIVE" : "DISABLED", disabledAt: parsed.data.active ? null : new Date() } }), prisma.user.update({ where: { id: target.userId }, data: { sessionVersion: { increment: 1 } } }), prisma.auditLog.create({ data: { actorUserId: context.userId, targetUserId: target.userId, targetCompanyId: parsed.data.companyId, action: parsed.data.active ? "MEMBER_REACTIVATED" : "MEMBER_REMOVED", details: { companyId: parsed.data.companyId, before: target.status, after: parsed.data.active ? "ACTIVE" : "DISABLED" } } })]); revalidatePath("/settings/members"); return { success: true, message: parsed.data.active ? "구성원을 재활성화했습니다." : "구성원을 비활성화했습니다." };
}
