import { useLocale, useTranslations } from "next-intl";import { differenceInCalendarDays } from "date-fns";
import { TriangleAlert } from "lucide-react";
import type { ConflictListItem, ConflictReservationItem } from "../reservation-conflict.types";
import { getReservationDisplayLabel } from "@/features/reservations/reservation-display";
import { getReservationSourceStatusLabel } from "@/features/reservations/reservation-status-meta";
import { EmptyState } from "@/components/shared/empty-state";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

function ReservationCell({ value }: {value: ConflictReservationItem;}) {const locale = useLocale();const i18n = useTranslations();const formatter = new Intl.DateTimeFormat(locale === "ja" ? "ja-JP" : "ko-KR", { year: "numeric", month: "2-digit", day: "2-digit", timeZone: "Asia/Tokyo" });return <div className="min-w-44"><p className="font-medium">{getReservationDisplayLabel(value, i18n("auto.m0397"))}</p><p className="text-xs text-muted-foreground">{formatter.format(value.startDate)} → {formatter.format(value.endDate)}</p><p className="text-xs text-muted-foreground">{value.calendarSourceName} · {getReservationSourceStatusLabel(value.status, i18n)}</p></div>;}
export function ReservationConflictList({ conflicts }: {conflicts: ConflictListItem[];}) {const locale = useLocale();const formatter = new Intl.DateTimeFormat(locale === "ja" ? "ja-JP" : "ko-KR", { year: "numeric", month: "2-digit", day: "2-digit", timeZone: "Asia/Tokyo" });const i18n = useTranslations();if (!conflicts.length) return <Card><CardContent className="flex min-h-72 items-center"><EmptyState icon={TriangleAlert} title={i18n("conflict.empty")} description={i18n("auto.m0374")} /></CardContent></Card>;return <><div className="grid gap-3 lg:hidden">{conflicts.map((conflict) => <Card key={conflict.id}><CardContent className="space-y-3 p-4"><div className="flex justify-between"><div><p className="font-semibold">{conflict.roomName}</p><p className="text-xs text-muted-foreground">{conflict.propertyName}</p></div><Badge variant={conflict.status === "ACTIVE" ? "destructive" : "outline"}>{i18n(`conflictStatus.${conflict.status}`)}</Badge></div><ReservationCell value={conflict.reservationA} /><ReservationCell value={conflict.reservationB} /><p className="text-xs font-medium text-amber-700 dark:text-amber-300">{i18n("auto.m0375")}{formatter.format(conflict.overlapStart)} → {formatter.format(conflict.overlapEnd)} · {differenceInCalendarDays(conflict.overlapEnd, conflict.overlapStart)}{i18n("auto.m0376")}</p></CardContent></Card>)}</div><Card className="hidden lg:block"><Table><TableHeader><TableRow><TableHead>{i18n("auto.m0005")}</TableHead><TableHead>{i18n("auto.m0377")}</TableHead><TableHead>{i18n("auto.m0378")}</TableHead><TableHead>{i18n("auto.m0379")}</TableHead><TableHead>{i18n("auto.m0380")}</TableHead><TableHead>{i18n("common.status")}</TableHead></TableRow></TableHeader><TableBody>{conflicts.map((conflict) => <TableRow key={conflict.id}><TableCell><p className="font-medium">{conflict.propertyName}</p><p className="text-xs text-muted-foreground">{conflict.roomName}</p></TableCell><TableCell><ReservationCell value={conflict.reservationA} /></TableCell><TableCell><ReservationCell value={conflict.reservationB} /></TableCell><TableCell>{formatter.format(conflict.overlapStart)} → {formatter.format(conflict.overlapEnd)}<p className="text-xs text-muted-foreground">{differenceInCalendarDays(conflict.overlapEnd, conflict.overlapStart)}{i18n("auto.m0376")}</p></TableCell><TableCell>{formatter.format(conflict.detectedAt)}</TableCell><TableCell><Badge variant={conflict.status === "ACTIVE" ? "destructive" : "outline"}>{i18n(`conflictStatus.${conflict.status}`)}</Badge></TableCell></TableRow>)}</TableBody></Table></Card></>;}
