import { differenceInCalendarDays } from "date-fns";
import { TriangleAlert } from "lucide-react";
import type { ConflictListItem, ConflictReservationItem } from "../reservation-conflict.types";
import { getReservationDisplayLabel } from "@/features/reservations/reservation-display";
import { EmptyState } from "@/components/shared/empty-state";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { RESERVATION_CONFLICT_UI } from "../reservation-conflict.labels";
const formatter = new Intl.DateTimeFormat("ko-KR", { year: "numeric", month: "2-digit", day: "2-digit", timeZone: "Asia/Tokyo" });
function ReservationCell({ value }: { value: ConflictReservationItem }) { return <div className="min-w-44"><p className="font-medium">{getReservationDisplayLabel(value)}</p><p className="text-xs text-muted-foreground">{formatter.format(value.startDate)} → {formatter.format(value.endDate)}</p><p className="text-xs text-muted-foreground">{value.calendarSourceName} · {value.status}</p></div>; }
export function ReservationConflictList({ conflicts }: { conflicts: ConflictListItem[] }) { if (!conflicts.length) return <Card><CardContent className="flex min-h-72 items-center"><EmptyState icon={TriangleAlert} title={RESERVATION_CONFLICT_UI.emptyTitle} description="동기화 시 같은 객실의 예약 기간이 겹치면 자동으로 표시됩니다." /></CardContent></Card>; return <><div className="grid gap-3 lg:hidden">{conflicts.map((conflict) => <Card key={conflict.id}><CardContent className="space-y-3 p-4"><div className="flex justify-between"><div><p className="font-semibold">{conflict.roomName}</p><p className="text-xs text-muted-foreground">{conflict.propertyName}</p></div><Badge variant={conflict.status === "ACTIVE" ? "destructive" : "outline"}>{conflict.status}</Badge></div><ReservationCell value={conflict.reservationA} /><ReservationCell value={conflict.reservationB} /><p className="text-xs font-medium text-amber-700 dark:text-amber-300">겹침 {formatter.format(conflict.overlapStart)} → {formatter.format(conflict.overlapEnd)} · {differenceInCalendarDays(conflict.overlapEnd, conflict.overlapStart)}박</p></CardContent></Card>)}</div><Card className="hidden lg:block"><Table><TableHeader><TableRow><TableHead>숙소 / 객실</TableHead><TableHead>예약 A</TableHead><TableHead>예약 B</TableHead><TableHead>겹치는 기간</TableHead><TableHead>감지</TableHead><TableHead>상태</TableHead></TableRow></TableHeader><TableBody>{conflicts.map((conflict) => <TableRow key={conflict.id}><TableCell><p className="font-medium">{conflict.propertyName}</p><p className="text-xs text-muted-foreground">{conflict.roomName}</p></TableCell><TableCell><ReservationCell value={conflict.reservationA} /></TableCell><TableCell><ReservationCell value={conflict.reservationB} /></TableCell><TableCell>{formatter.format(conflict.overlapStart)} → {formatter.format(conflict.overlapEnd)}<p className="text-xs text-muted-foreground">{differenceInCalendarDays(conflict.overlapEnd, conflict.overlapStart)}박</p></TableCell><TableCell>{formatter.format(conflict.detectedAt)}</TableCell><TableCell><Badge variant={conflict.status === "ACTIVE" ? "destructive" : "outline"}>{conflict.status}</Badge></TableCell></TableRow>)}</TableBody></Table></Card></>; }
