export const REVIEW_SYNC_CONCURRENCY = 4;
export const REVIEW_SYNC_STALE_RUNNING_MS = 20 * 60 * 1000;
export const REVIEW_SYNC_MAX_LISTINGS_PER_REQUEST = 100;
export const REVIEW_SYNC_MAX_REVIEWS_PER_LISTING = 100;
