import { BedDouble } from "lucide-react";
import type { PropertyOption } from "@/features/properties";
import type { RoomListItem } from "../room.types";
import { EmptyState } from "@/components/shared/empty-state";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { RoomActiveForm } from "./room-active-form";
import { RoomFormDialog } from "./room-form-dialog";
export function RoomList({ rooms, properties }: { rooms: RoomListItem[]; properties: PropertyOption[] }) { if (!rooms.length) return <Card><CardContent className="flex min-h-72 items-center"><EmptyState icon={BedDouble} title="조건에 맞는 객실이 없습니다" description="활성 숙소를 준비한 뒤 첫 객실을 등록하세요." /></CardContent></Card>; return <><div className="grid gap-3 md:hidden">{rooms.map((room) => <Card key={room.id}><CardContent className="space-y-3 p-4"><div className="flex justify-between"><div><p className="font-semibold">{room.name} <span className="font-normal text-muted-foreground">· {room.code}</span></p><p className="text-xs text-muted-foreground">{room.propertyName}{room.propertyIsActive ? "" : " · 비활성 숙소"}</p></div><Badge variant={room.isActive ? "secondary" : "outline"}>{room.isActive ? "활성" : "비활성"}</Badge></div><div className="flex justify-between text-xs text-muted-foreground"><span>수용 {room.capacity}명 · 순서 {room.sortOrder}</span><span>연동 {room.calendarSourceCount}개</span></div><div className="flex gap-2"><RoomFormDialog properties={properties} room={room} /><RoomActiveForm id={room.id} isActive={room.isActive} /></div></CardContent></Card>)}</div><Card className="hidden md:block"><Table><TableHeader><TableRow><TableHead>객실</TableHead><TableHead>숙소</TableHead><TableHead>수용 인원</TableHead><TableHead>정렬</TableHead><TableHead>연동</TableHead><TableHead>상태</TableHead><TableHead className="text-right">관리</TableHead></TableRow></TableHeader><TableBody>{rooms.map((room) => <TableRow key={room.id}><TableCell><p className="font-medium">{room.name}</p><p className="text-xs text-muted-foreground">{room.code}</p></TableCell><TableCell>{room.propertyName}{!room.propertyIsActive && <Badge className="ml-2" variant="outline">숙소 비활성</Badge>}</TableCell><TableCell>{room.capacity}명</TableCell><TableCell>{room.sortOrder}</TableCell><TableCell>{room.calendarSourceCount}개</TableCell><TableCell><Badge variant={room.isActive ? "secondary" : "outline"}>{room.isActive ? "활성" : "비활성"}</Badge></TableCell><TableCell><div className="flex justify-end gap-2"><RoomFormDialog properties={properties} room={room} /><RoomActiveForm id={room.id} isActive={room.isActive} /></div></TableCell></TableRow>)}</TableBody></Table></Card></>; }
