import "server-only";
import type { CalendarProviderType as DbProviderType } from "@/lib/generated/prisma/enums";
import { calendarProviderRegistry, CalendarFetchError, type CalendarProviderType } from "@/providers/calendar";
import { analyzeCalendar, CalendarParseError } from "./calendar-source.analysis";
import { createCalendarSource, findCalendarRoom, findCalendarSource, findDuplicateCalendarUrl, setCalendarSourceActive, updateCalendarSource } from "./calendar-source.repository";

type Input = { roomId: string; provider: CalendarProviderType; name: string; calendarUrl: string; isActive: boolean };
export class CalendarSourceServiceError extends Error { constructor(public readonly code: "ROOM_NOT_FOUND" | "DUPLICATE" | "INVALID_URL" | "NOT_FOUND" | "FETCH" | "PARSE", message: string) { super(message); this.name = "CalendarSourceServiceError"; } }

export function normalizeCalendarUrl(value: string): string { const url = new URL(value.trim()); url.hash = ""; return url.toString(); }
export function maskCalendarUrl(value: string): string { try { const url = new URL(value); const segments = url.pathname.split("/").map((segment) => segment.length > 12 ? `${segment.slice(0, 4)}********${segment.endsWith(".ics") ? ".ics" : ""}` : segment); const query = [...url.searchParams.keys()].map((key) => `${encodeURIComponent(key)}=********`).join("&"); return `${url.origin}${segments.join("/")}${query ? `?${query}` : ""}`; } catch { return "잘못된 URL"; } }
function validateProviderUrl(provider: CalendarProviderType, calendarUrl: string): string { let normalized: string; try { normalized = normalizeCalendarUrl(calendarUrl); } catch { throw new CalendarSourceServiceError("INVALID_URL", "올바른 HTTPS ICS URL을 입력해 주세요."); } const url = new URL(normalized); const handler = calendarProviderRegistry.get(provider); if (!handler.supportsUrl(url)) throw new CalendarSourceServiceError("INVALID_URL", "선택한 OTA와 URL 호스트가 일치하지 않습니다."); return normalized; }

export async function createCalendarSourceSafely(input: Input) { const calendarUrl = validateProviderUrl(input.provider, input.calendarUrl); const room = await findCalendarRoom(input.roomId); if (!room?.property) throw new CalendarSourceServiceError("ROOM_NOT_FOUND", "선택한 객실 또는 숙소가 존재하지 않습니다."); if (await findDuplicateCalendarUrl(input.roomId, calendarUrl)) throw new CalendarSourceServiceError("DUPLICATE", "같은 객실에 동일한 ICS URL이 이미 등록되어 있습니다."); return createCalendarSource({ ...input, provider: input.provider as DbProviderType, calendarUrl }); }
export async function updateCalendarSourceSafely(id: string, input: Omit<Input, "calendarUrl"> & { calendarUrl?: string }) { const existing = await findCalendarSource(id); if (!existing) throw new CalendarSourceServiceError("NOT_FOUND", "캘린더 연결을 찾을 수 없습니다."); const calendarUrl = input.calendarUrl ? validateProviderUrl(input.provider, input.calendarUrl) : existing.calendarUrl; if (!input.calendarUrl) validateProviderUrl(input.provider, calendarUrl); const room = await findCalendarRoom(input.roomId); if (!room?.property) throw new CalendarSourceServiceError("ROOM_NOT_FOUND", "선택한 객실 또는 숙소가 존재하지 않습니다."); if (await findDuplicateCalendarUrl(input.roomId, calendarUrl, id)) throw new CalendarSourceServiceError("DUPLICATE", "같은 객실에 동일한 ICS URL이 이미 등록되어 있습니다."); return updateCalendarSource(id, { ...input, provider: input.provider as DbProviderType, calendarUrl }); }
export async function changeCalendarSourceActive(id: string, isActive: boolean) { const existing = await findCalendarSource(id); if (!existing) throw new CalendarSourceServiceError("NOT_FOUND", "캘린더 연결을 찾을 수 없습니다."); if (existing.isActive === isActive) return existing; return setCalendarSourceActive(id, isActive); }
export async function testCalendarSourceConnection(id: string) { const source = await findCalendarSource(id); if (!source) throw new CalendarSourceServiceError("NOT_FOUND", "캘린더 연결을 찾을 수 없습니다."); if (!(["AIRBNB", "BOOKING", "AGODA"] as string[]).includes(source.provider)) throw new CalendarSourceServiceError("FETCH", "이 Provider는 아직 연결 테스트를 지원하지 않습니다."); const provider = calendarProviderRegistry.get(source.provider as CalendarProviderType); let url: URL; try { url = new URL(source.calendarUrl); } catch { throw new CalendarSourceServiceError("INVALID_URL", "저장된 캘린더 URL이 올바르지 않습니다."); } if (!provider.supportsUrl(url)) throw new CalendarSourceServiceError("INVALID_URL", "저장된 URL과 Provider가 일치하지 않습니다."); const started = performance.now(); try { const result = await provider.fetchCalendar({ calendarUrl: source.calendarUrl }); return analyzeCalendar(result, Math.round(performance.now() - started)); } catch (error) { if (error instanceof CalendarParseError) throw new CalendarSourceServiceError("PARSE", error.message); if (error instanceof CalendarFetchError) throw new CalendarSourceServiceError("FETCH", error.message); throw new CalendarSourceServiceError("FETCH", "캘린더 연결 테스트 중 알 수 없는 오류가 발생했습니다."); } }
