import test from "node:test";
import assert from "node:assert/strict";
import { createRoomRegistration, RoomRegistrationError } from "../create-room-registration";
import { prepareRoomCalendarDrafts } from "../room-calendar-draft";
import type { CalendarDraftConnectionResult } from "../../calendar-sources/calendar-source.types";

const room = { propertyId: "property", name: "테스트 객실", capacity: 2 };
const result = (provider: "AIRBNB" | "BOOKING" | "AGODA", url: string): CalendarDraftConnectionResult => ({ provider, submittedUrl: url, normalizedUrl: url, responseTimeMs: 1, fetchedAt: new Date(0).toISOString(), contentType: "text/calendar", eventCount: 1, uidCount: 1, startCount: 1, endCount: 1, summaryCount: 1 });
const atomic = async () => ({ id: "room" });

test("iCal URL이 없으면 Room만 생성한다", async () => { const prepared = prepareRoomCalendarDrafts([]); assert.equal(prepared.success, true); let count = -1; await createRoomRegistration({ room, calendars: [] }, { testConnection: async () => { throw new Error("호출되면 안 됨"); }, createAtomically: async (_room, calendars) => { count = calendars.length; return { id: "room" }; } }); assert.equal(count, 0); });
test("Airbnb 테스트 성공 후 Room과 CalendarSource를 생성한다", async () => { const calendars = [{ provider: "AIRBNB" as const, calendarUrl: "https://airbnb.com/a.ics", name: "테스트 객실 Airbnb" }]; let saved = 0; await createRoomRegistration({ room, calendars }, { testConnection: async (provider, url) => result(provider, url), createAtomically: async (_room, values) => { saved = values.length; return { id: "room" }; } }); assert.equal(saved, 1); });
test("여러 Provider를 검증 후 일괄 생성한다", async () => { const calendars = [{ provider: "AIRBNB" as const, calendarUrl: "https://airbnb.com/a.ics", name: "Airbnb" }, { provider: "BOOKING" as const, calendarUrl: "https://ical.booking.com/b.ics", name: "Booking.com" }]; let providers: string[] = []; await createRoomRegistration({ room, calendars }, { testConnection: async (provider, url) => result(provider, url), createAtomically: async (_room, values) => { providers = values.map((value) => value.provider); return { id: "room" }; } }); assert.deepEqual(providers, ["AIRBNB", "BOOKING"]); });
test("미테스트 URL은 저장 준비 단계에서 차단한다", () => { const prepared = prepareRoomCalendarDrafts([{ provider: "AIRBNB", calendarUrl: "https://airbnb.com/a.ics", testedCalendarUrl: "" }]); assert.equal(prepared.success, false); if (!prepared.success) assert.equal(prepared.errors.AIRBNB?.code, "UNTESTED"); });
test("URL 수정 시 기존 테스트 성공 상태를 무효화한다", () => { const prepared = prepareRoomCalendarDrafts([{ provider: "AIRBNB", calendarUrl: "https://airbnb.com/new.ics", testedCalendarUrl: "https://airbnb.com/old.ics" }]); assert.equal(prepared.success, false); });
test("연결 재검증 실패 URL은 생성 전에 차단한다", async () => { const calendars = [{ provider: "AGODA" as const, calendarUrl: "https://ycs.agoda.com/a.ics", name: "Agoda" }]; await assert.rejects(() => createRoomRegistration({ room, calendars }, { testConnection: async () => { throw new Error("ICS 형식 오류"); }, createAtomically: atomic }), RoomRegistrationError); });
test("CalendarSource 원자 생성 실패는 성공으로 처리하지 않는다", async () => { let persisted = false; await assert.rejects(() => createRoomRegistration({ room, calendars: [] }, { testConnection: async (provider, url) => result(provider, url), createAtomically: async () => { persisted = false; throw new Error("transaction rollback"); } })); assert.equal(persisted, false); });
test("중복 URL을 차단한다", () => { const url = "https://example.com/a.ics"; const prepared = prepareRoomCalendarDrafts([{ provider: "AIRBNB", calendarUrl: url, testedCalendarUrl: url }, { provider: "BOOKING", calendarUrl: url, testedCalendarUrl: url }]); assert.equal(prepared.success, false); if (!prepared.success) assert.equal(prepared.errors.BOOKING?.code, "DUPLICATE"); });
test("빈 Provider URL은 등록 대상에서 제외한다", () => { const prepared = prepareRoomCalendarDrafts([{ provider: "AIRBNB", calendarUrl: "   ", testedCalendarUrl: "" }]); assert.deepEqual(prepared, { success: true, drafts: [] }); });
test("미지원 Provider URL은 명시적으로 차단한다", () => { const prepared = prepareRoomCalendarDrafts([{ provider: "EXPEDIA", calendarUrl: "https://expedia.com/a.ics", testedCalendarUrl: "https://expedia.com/a.ics" }]); assert.equal(prepared.success, false); if (!prepared.success) assert.equal(prepared.errors.EXPEDIA?.code, "UNSUPPORTED"); });
test("기존 Room 기본정보 payload를 변경하지 않는다", async () => { let savedRoom: typeof room | null = null; await createRoomRegistration({ room, calendars: [] }, { testConnection: async (provider, url) => result(provider, url), createAtomically: async (value) => { savedRoom = value; return { id: "room" }; } }); assert.deepEqual(savedRoom, room); });
