"use client";

import { useActionState, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { ActionMessage } from "@/components/shared/action-message";
import type { ActionResult } from "@/lib/action-result";
import type { CompanyMemberRole } from "@/lib/generated/prisma/enums";
import { cancelInvitationAction, inviteCompanyMemberAction, resendInvitationAction, setCompanyMemberActiveAction, updateCompanyMemberAction, type InvitationActionResult } from "../member-management.actions";
import type { AwaitedReturn, ManagedMembership, PendingInvitation } from "../member-management.types";

const initial: ActionResult = { success: false, message: "" };
const invitationInitial: InvitationActionResult = { success: false, message: "" };
const date = new Intl.DateTimeFormat("ko-KR", { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Tokyo" });
const actionMessageState = (state: InvitationActionResult): ActionResult => state.success ? { success: true, message: state.message } : state;

function InviteForm({ companyId, properties }: { companyId: string; properties: Array<{ id: string; name: string }> }) {
  const [state, action, pending] = useActionState(inviteCompanyMemberAction, invitationInitial);
  const [role, setRole] = useState<CompanyMemberRole>("STAFF");
  return <Card><CardHeader><CardTitle>구성원 초대</CardTitle></CardHeader><CardContent><form action={action} className="grid gap-3 md:grid-cols-2"><input type="hidden" name="companyId" value={companyId} /><Input name="email" type="email" placeholder="이메일" required /><Input name="displayName" placeholder="이름 또는 표시 이름 (선택)" maxLength={50} /><select name="role" value={role} onChange={(event) => setRole(event.target.value as CompanyMemberRole)} className="h-8 rounded-lg border bg-background px-2 text-sm"><option value="ADMIN">관리자</option><option value="STAFF">직원</option></select><Input name="message" placeholder="초대 메시지 (선택)" maxLength={500} />{role === "STAFF" && <fieldset className="space-y-2 md:col-span-2"><legend className="text-sm font-medium">접근 가능한 숙소</legend><div className="flex flex-wrap gap-3">{properties.map((property) => <label key={property.id} className="flex items-center gap-1.5 text-sm"><input type="checkbox" name="propertyIds" value={property.id} />{property.name}</label>)}</div></fieldset>}<div className="flex flex-wrap items-center gap-3 md:col-span-2"><Button type="submit" disabled={pending}>{pending ? "초대 중..." : "구성원 초대"}</Button><ActionMessage state={actionMessageState(state)} />{state.success && state.data?.invitationUrl && <a className="break-all text-xs text-primary underline" href={state.data.invitationUrl}>개발용 초대 링크</a>}</div></form></CardContent></Card>;
}

function MemberCard({ membership, companyId, properties, actorUserId }: { membership: ManagedMembership; companyId: string; properties: Array<{ id: string; name: string }>; actorUserId: string }) {
  const [updateState, updateAction, updatePending] = useActionState(updateCompanyMemberAction, initial);
  const [activeState, activeAction, activePending] = useActionState(setCompanyMemberActiveAction, initial);
  const [role, setRole] = useState<CompanyMemberRole>(membership.role);
  const isSelf = membership.user.id === actorUserId;
  return <article className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">{membership.user.name}</p><p className="text-sm text-muted-foreground">{membership.user.email}</p><p className="text-xs text-muted-foreground">최근 로그인 {membership.user.lastLoginAt ? date.format(membership.user.lastLoginAt) : "없음"} · 가입 {date.format(membership.createdAt)}</p></div><div className="flex gap-1"><Badge variant="outline">{membership.role === "ADMIN" ? "관리자" : "직원"}</Badge><Badge variant={membership.status === "ACTIVE" ? "secondary" : "outline"}>{membership.status === "ACTIVE" ? "활성" : "비활성"}</Badge></div></div><details className="mt-3"><summary className="cursor-pointer text-sm font-medium">작업 메뉴</summary><div className="mt-3 space-y-3"><form action={updateAction} className="space-y-3 rounded-lg border p-3"><input type="hidden" name="companyId" value={companyId} /><input type="hidden" name="membershipId" value={membership.id} /><Input name="name" defaultValue={membership.user.name} required maxLength={50} /><select name="role" value={role} onChange={(event) => setRole(event.target.value as CompanyMemberRole)} disabled={isSelf} className="h-8 rounded-lg border bg-background px-2 text-sm"><option value="ADMIN">관리자</option><option value="STAFF">직원</option></select>{role === "STAFF" && <div className="flex flex-wrap gap-3">{properties.map((property) => <label key={property.id} className="flex items-center gap-1.5 text-sm"><input type="checkbox" name="propertyIds" value={property.id} defaultChecked={membership.propertyAccesses.some((item) => item.propertyId === property.id)} />{property.name}</label>)}</div>}<div className="flex items-center gap-2"><Button type="submit" size="sm" disabled={updatePending || isSelf}>저장</Button><ActionMessage state={updateState} /></div></form><form action={activeAction} className="flex items-center gap-2"><input type="hidden" name="companyId" value={companyId} /><input type="hidden" name="membershipId" value={membership.id} /><input type="hidden" name="active" value={String(membership.status !== "ACTIVE")} /><Button type="submit" size="sm" variant="outline" disabled={activePending || isSelf}>{membership.status === "ACTIVE" ? "비활성화" : "재활성화"}</Button><ActionMessage state={activeState} /></form></div></details></article>;
}

function InvitationCard({ invitation, companyId }: { invitation: PendingInvitation; companyId: string }) {
  const [cancelState, cancelAction, cancelPending] = useActionState(cancelInvitationAction, initial); const [resendState, resendAction, resendPending] = useActionState(resendInvitationAction, invitationInitial);
  const expired = invitation.expiresAt <= new Date();
  return <article className="rounded-xl border border-dashed p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">{invitation.displayName || "이름 미입력"}</p><p className="text-sm text-muted-foreground">{invitation.email}</p><p className="text-xs text-muted-foreground">초대한 사람 {invitation.invitedBy.name} · 만료 {date.format(invitation.expiresAt)}</p></div><div className="flex gap-1"><Badge variant="outline">{expired ? "초대 만료" : "초대 대기"}</Badge><Badge variant={invitation.mailStatus === "FAILED" ? "destructive" : "secondary"}>{invitation.mailStatus === "FAILED" ? "메일 실패" : invitation.role === "ADMIN" ? "관리자" : "직원"}</Badge></div></div><div className="mt-3 flex flex-wrap gap-2"><form action={resendAction}><input type="hidden" name="companyId" value={companyId} /><input type="hidden" name="invitationId" value={invitation.id} /><Button size="sm" variant="outline" disabled={resendPending}>다시 보내기</Button></form><form action={cancelAction}><input type="hidden" name="companyId" value={companyId} /><input type="hidden" name="invitationId" value={invitation.id} /><Button size="sm" variant="outline" disabled={cancelPending}>초대 취소</Button></form></div><ActionMessage state={resendState.success || resendState.message ? actionMessageState(resendState) : cancelState} />{resendState.success && resendState.data?.invitationUrl && <a className="mt-2 block break-all text-xs text-primary underline" href={resendState.data.invitationUrl}>개발용 초대 링크</a>}</article>;
}

export function MemberManagement({ result, companyId, properties, actorUserId }: { result: AwaitedReturn; companyId: string; properties: Array<{ id: string; name: string }>; actorUserId: string }) {
  return <div className="space-y-4"><InviteForm companyId={companyId} properties={properties} /><Card><CardHeader><CardTitle>구성원 목록 · {result.totalCount}명</CardTitle></CardHeader><CardContent><div className="grid gap-3 lg:grid-cols-2">{result.rows.map((row) => row.kind === "MEMBER" ? <MemberCard key={`m-${row.membership.id}`} membership={row.membership} companyId={companyId} properties={properties} actorUserId={actorUserId} /> : <InvitationCard key={`i-${row.invitation.id}`} invitation={row.invitation} companyId={companyId} />)}</div>{!result.rows.length && <p className="py-12 text-center text-sm text-muted-foreground">조건에 맞는 구성원이 없습니다.</p>}</CardContent></Card></div>;
}
