import { differenceInCalendarDays } from "date-fns";
import { CalendarRange, TriangleAlert } from "lucide-react";
import type { ReservationListItem } from "../reservation.types";
import { getReservationDisplayName } from "../reservation-display";
import { getCalendarProviderLabel } from "@/providers/calendar/types";
import { EmptyState } from "@/components/shared/empty-state";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatReservationConflictCount, RESERVATION_CONFLICT_UI } from "@/features/reservation-conflicts/reservation-conflict.labels";

const formatter = new Intl.DateTimeFormat("ko-KR", { month: "2-digit", day: "2-digit", year: "numeric", timeZone: "Asia/Tokyo" });
function ConflictDetails({ reservation }: { reservation: ReservationListItem }) {
  if (!reservation.activeConflictCount) return null;
  return <details className="relative"><summary className="list-none cursor-pointer"><Badge className="gap-1 bg-amber-500/15 text-amber-800 dark:text-amber-300" variant="outline"><TriangleAlert className="size-3" />{formatReservationConflictCount(reservation.activeConflictCount)}</Badge></summary><div className="mt-2 min-w-64 space-y-2 rounded-lg border bg-popover p-3 text-xs shadow-sm">{reservation.activeConflicts.map((other) => <div key={other.id} className="border-b pb-2 last:border-0 last:pb-0"><p className="font-medium">{getReservationDisplayName(other)} · {getCalendarProviderLabel(other.provider) ?? "예약"}</p><p className="text-muted-foreground">{formatter.format(other.startDate)} → {formatter.format(other.endDate)} · {differenceInCalendarDays(other.endDate, other.startDate)}박</p><p className="text-muted-foreground">{other.calendarSourceName} · {other.status}</p></div>)}{reservation.activeConflicts.length < reservation.activeConflictCount && <p className="text-muted-foreground">나머지 항목은 {RESERVATION_CONFLICT_UI.label} 전용 화면에서 확인하세요.</p>}</div></details>;
}

export function ReservationList({ reservations }: { reservations: ReservationListItem[] }) {
  if (!reservations.length) return <Card><CardContent className="flex min-h-72 items-center"><EmptyState icon={CalendarRange} title="조건에 맞는 예약이 없습니다" description="캘린더 연결을 동기화하거나 필터 기간을 변경해 보세요." /></CardContent></Card>;
  return <><div className="grid gap-3 md:hidden">{reservations.map((reservation) => <Card key={reservation.id}><CardContent className="space-y-3 p-4"><div className="flex justify-between"><div><p className="font-semibold">{reservation.roomName}</p><p className="text-xs text-muted-foreground">{reservation.propertyName}</p></div><Badge variant={reservation.status === "CANCELLED" ? "outline" : "secondary"}>{reservation.status}</Badge></div><p className="text-sm">{formatter.format(reservation.startDate)} → {formatter.format(reservation.endDate)} · {differenceInCalendarDays(reservation.endDate, reservation.startDate)}박</p><div className="flex justify-between text-xs text-muted-foreground"><span>예약자: {getReservationDisplayName(reservation)}</span><Badge variant="outline">{getCalendarProviderLabel(reservation.provider) ?? "예약"}</Badge></div><ConflictDetails reservation={reservation} /></CardContent></Card>)}</div><Card className="hidden md:block"><Table><TableHeader><TableRow><TableHead>체크인</TableHead><TableHead>체크아웃</TableHead><TableHead>숙박</TableHead><TableHead>예약자</TableHead><TableHead>숙소 / 객실</TableHead><TableHead>OTA</TableHead><TableHead>상태</TableHead><TableHead>{RESERVATION_CONFLICT_UI.label}</TableHead></TableRow></TableHeader><TableBody>{reservations.map((reservation) => <TableRow key={reservation.id}><TableCell>{formatter.format(reservation.startDate)}</TableCell><TableCell>{formatter.format(reservation.endDate)}</TableCell><TableCell>{differenceInCalendarDays(reservation.endDate, reservation.startDate)}박</TableCell><TableCell>{getReservationDisplayName(reservation)}</TableCell><TableCell><p className="font-medium">{reservation.propertyName}</p><p className="text-xs text-muted-foreground">{reservation.roomName}</p></TableCell><TableCell><Badge variant="outline">{getCalendarProviderLabel(reservation.provider) ?? "예약"}</Badge></TableCell><TableCell><Badge variant={reservation.status === "CANCELLED" ? "outline" : "secondary"}>{reservation.status}</Badge></TableCell><TableCell><ConflictDetails reservation={reservation} /></TableCell></TableRow>)}</TableBody></Table></Card></>;
}
