import { differenceInCalendarDays } from "date-fns";
import { CalendarRange } from "lucide-react";
import type { ReservationListItem } from "../reservation.types";
import { EmptyState } from "@/components/shared/empty-state";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

const formatter = new Intl.DateTimeFormat("ko-KR", { month: "2-digit", day: "2-digit", year: "numeric", timeZone: "Asia/Tokyo" });
export function ReservationList({ reservations }: { reservations: ReservationListItem[] }) { if (!reservations.length) return <Card><CardContent className="flex min-h-72 items-center"><EmptyState icon={CalendarRange} title="조건에 맞는 예약이 없습니다" description="캘린더 연결을 동기화하거나 필터 기간을 변경해 보세요." /></CardContent></Card>; return <><div className="grid gap-3 md:hidden">{reservations.map((reservation) => <Card key={reservation.id}><CardContent className="space-y-3 p-4"><div className="flex justify-between"><div><p className="font-semibold">{reservation.roomName}</p><p className="text-xs text-muted-foreground">{reservation.propertyName}</p></div><Badge variant={reservation.status === "CANCELLED" ? "outline" : "secondary"}>{reservation.status}</Badge></div><p className="text-sm">{formatter.format(reservation.startDate)} → {formatter.format(reservation.endDate)} · {differenceInCalendarDays(reservation.endDate, reservation.startDate)}박</p><div className="flex justify-between text-xs text-muted-foreground"><span>Guest: {reservation.guestName ?? "비공개"}</span><Badge variant="outline">{reservation.provider}</Badge></div></CardContent></Card>)}</div><Card className="hidden md:block"><Table><TableHeader><TableRow><TableHead>체크인</TableHead><TableHead>체크아웃</TableHead><TableHead>숙박</TableHead><TableHead>Guest</TableHead><TableHead>숙소 / 객실</TableHead><TableHead>Provider</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{reservations.map((reservation) => <TableRow key={reservation.id}><TableCell>{formatter.format(reservation.startDate)}</TableCell><TableCell>{formatter.format(reservation.endDate)}</TableCell><TableCell>{differenceInCalendarDays(reservation.endDate, reservation.startDate)}박</TableCell><TableCell>{reservation.guestName ?? "비공개"}</TableCell><TableCell><p className="font-medium">{reservation.propertyName}</p><p className="text-xs text-muted-foreground">{reservation.roomName}</p></TableCell><TableCell><Badge variant="outline">{reservation.provider}</Badge></TableCell><TableCell><Badge variant={reservation.status === "CANCELLED" ? "outline" : "secondary"}>{reservation.status}</Badge></TableCell></TableRow>)}</TableBody></Table></Card></>; }
